defaults:
  - _self_
  - prob: tsp
  - dd: exact
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

from_pid: 0
to_pid: 1000
n_processes: 1
split: train
dd_type: ${dd.type}
seed: 7
save_dd: true

time_limit: 1800

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
