defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# General settings
n_objs: 3
n_vars: 100
size: # To be assigned by the script

# Objective and constraint coefficient ranges
obj_lb: 1
obj_ub: 100
# cons_lb: 1
# cons_ub: 1000

# Number of instances to generate
n_train: 1000
n_test: 100
n_val: 100
seed: 7

zip_output: false

# Setpacking specific settings
graph_type: stidsen
vars_per_con: 10 # for Stidsen graphs

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
