defaults:
  - _self_
  - prob: knapsack
  - dd: exact
  - model: gbt
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

from_pid: 0
to_pid: 1000
n_processes: 1
split: train
dd_type: ${dd.type}
seed: 7
save_dd: false

time_limit: 1800

dataset:
  version: 1
  train:
    from_pid: 0
    to_pid: 1000
  val:
    from_pid: 1000
    to_pid: 1100
  test:
    from_pid: 1100
    to_pid: 1200

bdd_data:
  # Use parent data used to characterize node information
  with_parent: false
  # Number of negative samples used per positive sample
  neg_to_pos_ratio: 1
  min_samples: 0
  flag_layer_penalty: true
  layer_penalty: exponential
  flag_imbalance_penalty: false
  flag_importance_penalty: 1
  penalty_aggregation: sum
  label: binary

device: cpu

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
